PROYECTO MCSD - AZURE/WilsonInformer/Models/Parte.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper.Configuration;

namespace WilsonInformer.Models
{
    public class Parte
    {
        public String N_parte { get; set; }
        public String Envios { get; set; }
        public int Bult { get; set; }
        public DateTime F_Albaran { get; set; }

        public String Orig { get; set; }
        public String Dest { get; set; }
        public String Propi { get; set; }
        public String Serv { get; set; }
        public String Abonado { get; set; }

        public String Tipo { get; set; }

        public String Estado { get; set; }

        public String Gestor { get; set; }

        public String Resolucion { get; set; }

        public DateTime Fecha_parte { get; set; }

        public DateTime Fecha_resolucion { get; set; }


        public String Fecha_parteString { get; set; }

        public String Fecha_resolucionString { get; set; }
  
        public String F_AlbaranString { get; set; }

        public String Tiempo { get; set; }
        public String Accion { get; set; }


        public String GetAlbaran(String Envios)
        {
            return Envios.Substring(0, 12);
        }
        public String GetEnvio(String Envios)
        {
            return Envios.Remove(0, 12);
        }
        


    }
    public class ParteMap : ClassMap<Parte>
    {
        public ParteMap()
        {
            Map(l => l.N_parte).Name("N. parte");
            Map(l => l.Envios).Name("Envios");
            Map(l => l.Bult).Name("Bult");
            Map(l => l.F_AlbaranString).Name("F. Albaran");
            Map(l => l.Orig).Name("Orig.");
            Map(l => l.Dest).Name("Dest.");
            Map(l => l.Propi).Name("Propi.");
            Map(l => l.Serv).Name("Serv.");
            Map(l => l.Abonado).Name("Abonado");
            Map(l => l.Tipo).Name("Tipo");
            Map(l => l.Estado).Name("Estado");
            Map(l => l.Gestor).Name("Gestor");
            Map(l => l.Resolucion).Name("Resolución");
            Map(l => l.Fecha_parteString).Name("Fecha parte");
            Map(l => l.Fecha_resolucionString).Name("F.Resolución");
            Map(l => l.Accion).Name("Acción");
        }
    }
}

PROYECTO MCSD - AZURE/WilsonInformer/Controllers/PartesController.cs
using CsvHelper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WilsonInformer.Filter;
using WilsonInformer.Helpers;
using WilsonInformer.Models;
using WilsonInformer.Utility;
using WSegInformer.Utility;
using X.PagedList;
using PdfSharp;
using PdfSharp.Pdf;
using TheArtOfDev.HtmlRenderer.PdfSharp;
using TheArtOfDev.HtmlRenderer;
using GrapeCity;
using GrapeCity.Documents.Html;
using WilsonInformer.Services;
using Microsoft.Extensions.Logging;
using System.Drawing;
using System.Threading;
using System.Text;
using System.Security.Claims;

namespace WilsonInformer.Controllers
{
    [AuthorizeUsers]
    public class PartesController : Controller
    {
        //private IRepositoryPartes repos;
        private PathProvider provider;
        public ILogger _logger;
        private ServicePartes service;

        public PartesController(ServicePartes service,PathProvider provider,ILogger<PartesController> _logger)
        {
            this._logger = _logger;
            this.service = service;
            this.provider = provider;
            
        }
        public async Task<IActionResult> QuienesSomos()
        {
            return View();
        }
        public async Task<IActionResult> Index()
        {
            List<Parte> partes = await service.GetPartesDB(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            List<Parte> partescerrados = await service.GetPartesCerrados(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            List<Parte> partesentregados = await service.GetPartesEntregadosEnGestion(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            if(partes == null)
            {
                ViewBag.TotalPartes = 0;
                ViewBag.Cerrados = 0;
                ViewBag.CerradosSF = 0;
                ViewBag.EntregadosEnGestion = 0;

            }
            else
            {
                ViewBag.TotalPartes = partes.Count();
                ViewBag.Cerrados = partescerrados.Count();
                ViewBag.CerradosSF = await service.GetNumPartesCerradosSinF(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
                ViewBag.EntregadosEnGestion = partesentregados.Count();
            }
            return View();
        }

        public async Task<IActionResult> DeleteAllPartes()
        {
            await service.ClearDB(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            return RedirectToAction("UploadPartes",new{ deleted =true});
        }
        public IActionResult UploadPartes(bool? deleted)
        {
            if (deleted!=null)
            {
                ViewBag.Message = "Datos borrados con exito";

                ViewBag.type = "alert alert-success";
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadPartes(List<IFormFile> postedFiles)
        {
            if (postedFiles.Count > 0)
            {
                IFormFile file = postedFiles.First();
                if (file.FileName.EndsWith(".csv"))
                {
                    try
                    {
                        List<Parte> partesCsv = ReadCSV(file);
                        if (partesCsv != null)
                        {
                            int afectados = await service.InsertListaPartes(partesCsv,HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
                            if (afectados > 0)
                            {
                                ViewBag.Message = "Cargado con exito.";

                                ViewBag.type = "alert alert-success";
                                return View();
                            }
                            else
                            {
                                ViewBag.Message = "No se insertaron nuevos partes.";
                                ViewBag.type = "alert alert-danger";
                                return View();
                            }
                        }
                        else
                        {
                            ViewBag.Message = "Error al leer Fichero, " +
                           "los registros del fichero pueden " +
                           "no ser validos.";
                            ViewBag.type = "alert alert-danger";
                            return View();
                        }
                        
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "Error al leer Fichero, " +
                            "los registros del fichero pueden " +
                            "no ser validos.";
                        ViewBag.type = "alert alert-danger";
                        return View();
                    }
                }
                else
                {
                    ViewBag.Message = "Error: " + file.FileName + " puede no ser un fichero CSV";
                    ViewBag.type = "alert alert-danger";
                    return View();
                }
            }
            else
            {
                ViewBag.Message = "Seleccione un fichero";
                ViewBag.type = "alert alert-warning";
                return View();
            }
        }
        public List<Parte> ReadCSV(IFormFile file)
        {
            using (var reader = new StreamReader(file.OpenReadStream()))
            using (var csvReader = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                {
                    try
                    {
                        csvReader.Configuration.RegisterClassMap<ParteMap>();
                        //var records = csvReader.GetRecords<Parte>().ToList();
                        //int afectados = InsertListaPartes(records);
                        //return afectados;
                        List<Parte> records = csvReader.GetRecords<Parte>().ToList();
                        return records;
                    }
                    catch (Exception ex)
                    {
                        return null;
                    }
                }
            }
        }
        public async Task<IActionResult> GetPartes(int? page, String? nalbaran, String? nparte, DateTime? dateFrom, DateTime? dateTo)
        {
            List<Parte> partes = new List<Parte>();
            if (nalbaran != null || nparte != null)
            {
                ViewBag.searchValPAR = nparte;
                ViewBag.searchValALB = nalbaran;

                partes = await service.GetPartesDBAlbaranParte(nalbaran, nparte,HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            }
            else
            {
                partes = await  service.GetPartesDB(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            }


            if (dateFrom != null && dateTo != null)
            {
                partes = await service.GetPartesFecha(dateTo.Value, dateFrom.Value,partes,HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));

                ViewBag.FilteredFecha = true;
                ViewBag.DateFrom = dateFrom;
                ViewBag.DateTo = dateTo;

                Dictionary<String, int> partesporfecha = await service.SetPartesFechaGraphicData(partes,HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));

                String[] cadenasinfo = partesporfecha.Keys.ToArray();
                String fechas = "[\""+string.Join("\",\"", cadenasinfo)+"\"]";
                
                int[] cadenasinfoPartes = partesporfecha.Values.ToArray();
                String npartes = "["+string.Join(",", cadenasinfoPartes)+"]";

                ViewBag.Npartes = npartes;
                ViewBag.Fechas = fechas;
             
            }
            if (partes != null)
            {
                ViewBag.Resultados = partes.Count();
                return View(partes.ToPagedList(page ?? 1, 50));
            }
            else
            {
                return View();
            }
           
        }

        [HttpPost]
        public IActionResult GetPartes(String nalbaran, String nparte, DateTime dateFrom, DateTime dateTo)
        {
            if (dateFrom == default(DateTime) || dateTo == default(DateTime))
            {
                return RedirectToAction("GetPartes", new { nparte = nparte, nalbaran = nalbaran });
            }
            else
            {
                return RedirectToAction("GetPartes", new { nparte = nparte, nalbaran = nalbaran, dateTo = dateTo, dateFrom = dateFrom });
            }
        }

        public async Task<IActionResult> PartePerdida(String nparte, bool? error)
        {
            var map = MapSelectResParte.GetMapResultados();
            ViewBag.resultados = map;
            Parte parte = await service.GetParte(nparte,HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            if (error == true)
            {
                ViewBag.type = "alert alert-danger";
                ViewBag.Error = "Seleccione un resultado final";
            }
            if (parte != null)
            {
                ViewBag.nparte = parte.N_parte;
                
                return View(parte);
            }
            else
            {

PROYECTO MCSD - AZURE/WilsonInformer/ViewComponents/EstadisticasAbonadoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WilsonInformer.Services;

namespace WilsonInformer.ViewComponents
{
    public class EstadisticasAbonadoViewComponent : ViewComponent
    {

        private ServicePartes service;

        public EstadisticasAbonadoViewComponent (ServicePartes service)
        {
            this.service = service;

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
        //    Dictionary<string, int> dataFO = repos.GetFramquiciasOrigen();
        //    Dictionary<string, int> dataFD = repos.GetFramquiciasDestino();

            Dictionary<string, int> dataAbonado = await service.GetAbonados(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));
            if (dataAbonado != null)
            {
                List<String> cadenasinfo = new List<string>();
                foreach (KeyValuePair<string, int> elem in dataAbonado)
                {
                    String s = "[\"" + elem.Key.Replace("\'", " ") + "\"," + elem.Value + "]";
                    cadenasinfo.Add(s);
                }
                String[] cadenas = cadenasinfo.ToArray();
                string abonadosstring = string.Join(",", cadenas);
                ViewBag.Propis = abonadosstring;
                ViewBag.Max = dataAbonado.FirstOrDefault().Value;
                ViewBag.Count = dataAbonado.Count;
            }

            return View();
        }
    }
}

PROYECTO MCSD - AZURE/WilsonInformer/ViewComponents/EstadisticasEstadoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WilsonInformer.Services;

namespace WilsonInformer.ViewComponents
{
    public class EstadisticasEstadoViewComponent : ViewComponent
    {
        public ServicePartes service;
        public EstadisticasEstadoViewComponent (ServicePartes service)
        {
            this.service = service;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            Dictionary<string, int> data = await service.GetEstados(HttpContext.User.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"));

            if (data != null)
            {
                int total = 0;
                foreach (var dato in data)
                {
                    total += dato.Value;
                }
                ViewBag.Total = total;
                ViewBag.Data = data;

            }
            return View();
            //@await Component.InvokeAsync("EstadisticasEstado")
        }
    }
}

PROYECTO MCSD - AZURE/WilsonInformer/Views/Partes/EntregadosEnGestion.cshtml
@model IPagedList<Parte>

<h1><b>Entregados - En gestión</b></h1>
<hr />

<a class="btn btn-light" style="margin-top:7px"
   href="@Url.Action("GetPartes", "Partes",new { })">
    Volver a ver Todos
</a>
    @if (Model != null)
    {
        <br/>
        <hr />
       <a style="margin-top:7px;margin-bottom:7px"><b>Partes: </b>@ViewBag.Resultados</a>
        <hr />
        @Html.PagedListPager(Model, page => Url.Action("EntregadosEnGestion", new { page }), new PagedListRenderOptions
   {
       Display = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
       DisplayLinkToIndividualPages = true,
       DisplayPageCountAndCurrentLocation = false,
       MaximumPageNumbersToDisplay = 15,
       LiElementClasses = new string[] { "page-item" },
       PageClasses = new string[] { "page-link" },
   })

       @section styles{ 
             <style>
                .child {
                    display: none;
                    padding-left: 50px;
                    color: blue;
                }

                .expand {
                    cursor: pointer;
                    vertical-align: top
                }
            </style>
       }
        <table class="table table-responsive-sm table-hover table-bordered" style="background-color:white">
            <thead style="background-color:black;color:white">
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Nº parte</th>
                    <th>Nº Albaran</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Parte p in Model)
                {
                    var color = "";
                    @if (p.Estado.Contains("Cerrada"))
                    {
                        color = "red";
                    }
                    else
                    {
                        color = "green";
                    }
                    <tr>
                        <td><input type="checkbox" style="width:30px;height:30px" /></td>
                        <td rowspan="2" style="background-color: @color">
                        </td>
                        <td>
                            <a asp-action="PartePerdida" asp-route-nparte="@p.N_parte" target="_blank">
                                <img style="width:30px;height:30px" src="~/assets/images/doc.png" />
                            </a>
                        </td>
                        <td style="padding-right:20px"><a href="@p.Accion" target="_blank">@p.N_parte</a></td>
                        <td>@p.GetAlbaran(p.Envios)</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="expand">[+]</td>
                        <td colspan="6">
                            <b>Estado:</b>
                            <table class="child">
                                <tr>
                                    <td style="color:white;background-color:@color">@p.Estado</td>
                                </tr>
                                <tr><td style="color:white;background-color:@color">@p.GetEnvio(p.Envios)</td></tr>
                                <tr>
                                    <td>
                                        <dl>
                                            <dt>Fecha de Parte:</dt>
                                            <dd>@p.Fecha_parte.ToString("dd/MM/yyyy")</dd>
                                            <dt>Fecha de Albaran:</dt>
                                            <dd>@p.F_Albaran.ToString("dd/MM/yyyy")</dd>
                                            <dt>Fecha de Resolución:</dt>

                                            @if (p.Fecha_resolucion.ToString("dd/MM/yyyy") == "01/01/0001")
                                            {
                                                <dd style="color:red">Sin fecha de resolución</dd>

                                            }
                                            else
                                            {
                                                <dd>@p.Fecha_resolucion.ToString("dd/MM/yyyy")</dd>
                                            }
                                        </dl>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
       @section scripts{ 
             <script>
            $('.expand').click(function () {
                var $td = $(this);

                if ($td.text() == '[+]') {
                    $td.text('[-]');
                    $td.next().children('table').show()
                } else {
                    $td.text('[+]');
                    $td.next().children('table').hide()
                }
            })
        </script>
       }

    }
    

PROYECTO MCSD - AZURE/WilsonInformer/Views/Partes/Estadisticas.cshtml
<h1>Estadísticas</h1>

@await Component.InvokeAsync("EstadisticasAbonado")

@await Component.InvokeAsync("EstadisticasEstado")

PROYECTO MCSD - AZURE/WilsonInformer/Views/Partes/GetPartes.cshtml
@model IPagedList<Parte>

    <h1><b>Buscar Partes</b></h1>
    @if (Model != null)
    {

        <hr />
        <a class="btn btn-info" style="width:500px" href='@Url.Action("EntregadosEnGestion", "Partes",new { })'>Gestión - Entregados</a>
        <a class="btn btn-info" style="width:500px" href='@Url.Action("Pendientes15", "Partes",new { })'>Gestión - Pendientes (15 dias atras)</a>
        <form method="post">

            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker7'>
                        <hr />
                    </div>
                </div>
            </div>
            <input type="number" value="1" name="page" hidden />
            <input class="form-control form-control-sm ml-3 w-75" style="float:left"
                   type="text" placeholder="Nº Albaran"
                   aria-label="Search" name="nalbaran" value="@ViewBag.searchValALB" />
            <input class="form-control form-control-sm ml-3 w-75" style="float:left"
                   type="text" placeholder="Nº Parte"
                   aria-label="Search" name="nparte" value="@ViewBag.searchValPAR" />
            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker7'>
                        <hr />
                    </div>
                </div>
            </div>
            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker6'>
                        <h4>Fecha Albaran</h4>
                    </div>
                </div>
            </div>
            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker6'>
                        <input class="form-control" id="date" name="dateFrom" placeholder="MM/DD/YYY" type="date" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker6'>
                        <a>a</a>
                    </div>
                </div>
            </div>
            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker7'>
                        <input id="date" class="form-control" name="dateTo" placeholder="MM/DD/YYY" type="date" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-3'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker7'>
                        <hr />
                    </div>
                </div>
            </div>


            <button type="submit" class="btn btn-info" style="width:75%">Buscar</button>
        </form>
        <hr/>
        <p><b>Partes: </b>@ViewBag.Resultados</p>
        <hr/>
        @*<p>@ViewBag.Resultados</p><br />*@
        @if (ViewBag.FilteredFecha != null)
        {
            <script src="https://code.highcharts.com/highcharts.js"></script>
            <script src="https://code.highcharts.com/modules/exporting.js"></script>
            <script src="https://code.highcharts.com/modules/export-data.js"></script>
            <script src="https://code.highcharts.com/modules/accessibility.js"></script>

            <figure class="highcharts-figure">
                <div id="container"></div>
                
            </figure>
            <script>
                Highcharts.chart('container', {
                    chart: {
                        type: 'line'
                    },
                    title: {
                        text: 'Evolución'
                    },
                    
                    xAxis: {
                        categories:@Html.Raw(ViewBag.Fechas)
                    },
                    yAxis: {
                        title: {
                            text: 'Nº Partes'
                        }
                    },
                    plotOptions: {
                        line: {
                            dataLabels: {
                                enabled: true
                            },
                            enableMouseTracking: false
                        }
                    },
                    series: [{
                        name: 'Partes',
                        data: @Html.Raw(ViewBag.Npartes)
                    }]
                });
            </script>
            <hr />

        }
        
        @Html.PagedListPager(Model, page => Url.Action("GetPartes", new
        {
       page,
            nalbaran = ViewBag.searchValALB,
       nparte = ViewBag.searchValPAR,
       dateTo = ViewBag.DateTo,
       dateFrom = ViewBag.DateFrom
        }),
       new PagedListRenderOptions
   {
       Display = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
       DisplayLinkToIndividualPages = true,
       DisplayPageCountAndCurrentLocation = false,
       MaximumPageNumbersToDisplay = 15,
       LiElementClasses = new string[] { "page-item" },
       PageClasses = new string[] { "page-link" },
   })
       @section styles{ 
             <style>
                .child {
                    display: none;
                    padding-left: 50px;
                    color: blue;
                }

                .expand {
                    cursor: pointer;
                    vertical-align: top
                }
            </style>
       }
        <table class="table table-responsive-sm table-hover table-bordered" style="background-color:white">
            <thead style="background-color:black;color:white">
                <tr>
                    <th></th>
                    <th></th>
                    <th>Nº parte</th>
                    <th>Nº Albaran</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Parte p in Model)
                {
                    var color = "";
                    @if (p.Estado.Contains("Cerrada"))
                    {
                        color = "red";
                    }
                    else
                    {
                        color = "green";
                    }
                    <tr>
                        <td rowspan="2" style="background-color: @color"></td>
                        <td>
                            <a asp-action="PartePerdida" asp-route-nparte="@p.N_parte" target="_blank">
                                <img style="width:30px;height:30px" src="~/assets/images/doc.png" />
                            </a>
                        </td>
                        <td style="padding-right:20px"><a href="@p.Accion" target="_blank">@p.N_parte</a></td>
                        <td>@p.GetAlbaran(p.Envios)</td>
                    </tr>
                    <tr>
                        <td class="expand">[+]</td>
                        <td colspan="6">
                            <b>Estado:</b>
                            <table class="child">
                                <tr>
                                    <td style="color:white;background-color:@color">@p.Estado</td>
                                </tr>
                                <tr><td style="color:white;background-color:@color">@p.GetEnvio(p.Envios)</td></tr>
                                <tr>
                                    <td>
                                        <dl>
                                            <dt>Fecha de Parte:</dt>
                                            <dd>@p.Fecha_parte.ToString("dd/MM/yyyy")</dd>
                                            <dt>Fecha de Albaran:</dt>
                                            <dd>@p.F_Albaran.ToString("dd/MM/yyyy")</dd>
                                            <dt>Fecha de Resolución:</dt>

                                            @if (p.Fecha_resolucion.ToString("dd/MM/yyyy") == "01/01/0001")
                                            {
                                                <dd style="color:red">Sin fecha de resolución</dd>

                                            }
                                            else
                                            {
                                                <dd>@p.Fecha_resolucion.ToString("dd/MM/yyyy")</dd>
                                            }
                                        </dl>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @section scripts{ 
            <script>
                $('.expand').click(function () {
                    var $td = $(this);

                    if ($td.text() == '[+]') {
                        $td.text('[-]');
                        $td.next().children('table').show()
                    } else {
                        $td.text('[+]');
                        $td.next().children('table').hide()
                    }
                })
            </script>
        }

    }
    else
    {
        <h1>No hay datos registrados</h1>
    }

PROYECTO MCSD - AZURE/WilsonInformer/Views/Partes/UploadPartes.cshtml
@*@model List<Parte>*@

    <h1>Actualizar Datos</h1>
    <hr />
    <div style="
    background-color: cornflowerblue;
    border: 1px solid blue;
    border-collapse: collapse;
    color:white;
    padding:15px">
        <p>
            Importe partes de pérdidas de <a href="https://wilsonapp.tech/auth/login"> https://wilsonapp.tech/</a>
            al servidor para poder comenzar a generar informes
        </p>
        <form method="post" enctype="multipart/form-data" asp-controller="Partes" asp-action="UploadPartes">
            @Html.AntiForgeryToken()
            <span>Seleccione CSV: </span>
            <input type="file" name="postedFiles" accept=".csv" class="form-group" />
            <button type="submit" class="btn btn-light">Cargar</button>
            <br />
        </form>

    </div>
    <a class="btn btn-danger" style="width:100%" href='@Url.Action("DeleteAllPartes", "Partes",new { })'>Limpiar datos almacenados</a>
    <hr />

    <div class="@ViewBag.type" role="alert">
        @Html.Raw(ViewBag.Message)
    </div>
    