MDFS-5/Azure_BlobStorage/MVCCoreStorageFile/MVCCoreStorageFile/Controllers/AzureBlobController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCCoreStorageFile.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreStorageFile.Controllers
{
    public class AzureBlobController : Controller
    {
        ServiceStorageBlob service;
        public AzureBlobController(ServiceStorageBlob service)
        {
            this.service = service;
        }
        public async Task<IActionResult> Index()
        {
            return View(await service.GetContainers());
        }

        public async Task<IActionResult> CreateContainer(String containerName)
        {
            await service.CreateContainseAsync(containerName);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Container(String containerName)
        {
            ViewBag.Container = containerName;
            return View(await service.GetFiles(containerName));
        }
        [HttpPost]
        public async Task<IActionResult> Container(IFormFile file,String container)
        {
            try
            {
                using (Stream stream = file.OpenReadStream())
                {
                    await service.Upload(file.FileName, stream, container);
                }
                return RedirectToAction("Container", new { containerName = container });
            }catch(Exception ex)
            {
                ViewBag.Mensaje = "Ya existe el fichero";
                ViewBag.Container = container;
                return View(await service.GetFiles(container));
            }
        }
        public async Task<IActionResult> Delete(String fileName,String containerName)
        {
            await service.Delete(fileName, containerName);
            return RedirectToAction("Container", new { containerName = containerName });
        }
        public async Task<IActionResult> DeleteContainer(String containerName)
        {
            await service.DeleteCOntainer(containerName);
            return RedirectToAction("Index");
            
        }
    }
}

MDFS-5/Azure_BlobStorage/MVCCoreStorageFile/MVCCoreStorageFile/Views/AzureBlob/Container.cshtml
@model List<Blob>
@section csss{
    <style>
        .wrapper {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            grid-gap: 10px;
        }
    </style>
}
<h1>Container</h1>
<hr />
<form method="post" enctype="multipart/form-data">
    <input type="text" name="container" value="@ViewBag.Container" hidden />
    <input type="file" name="file" />
    <button class="btn btn-warning" type="submit">Subir</button>
</form>
<br/>
<a style="color:red">@ViewBag.Mensaje</a>
<hr />

<div>
    <div class="wrapper">

        @foreach (Blob s in Model)
        {
        <div>
            <a asp-action="Delete" asp-route-fileName="@s.Nombre"
               asp-route-containerName="@ViewBag.Container"
               class="btn btn-danger">
                X
            </a>
            <img href="@s.Uri" style="width:200px;height:200px" src="@s.Uri" /><br />

        </div>
        }
    </div>
</div>

MDFS-5/Azure_BlobStorage/MVCCoreStorageFile/MVCCoreStorageFile/Views/AzureBlob/Index.cshtml
@model List<String>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<hr/>
<form method="post" asp-action="CreateContainer" asp-controller="AzureBlob">
    <input type="text"name="containerName"/>
    <button class="btn btn-warning" type="submit">Crear</button>
</form>
<hr/>

<table class="table table-hover">
    <thead>
        <tr>
            <td>Container</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (String s in Model)
        {
            <tr>
                <td>
                    <a asp-action="Container"
                       asp-controller="AzureBlob"
                       asp-route-containerName="@s">
                        @s
                    </a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-action="DeleteContainer" asp-controller="AzureBlob" asp-route-containerName="@s">X</a>
                </td>
        </tr>
    }
    </tbody>
</table>
   