MDFS-4/NetCore/ProyectoCeroEF/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoCeroEF.Models
{
    [Table("DEPT")]
    public class Departamento
    {
        [Key]
        [Column("DEPT_NO")]
        public int Dept_NO { get; set; }
        [Column("DNOMBRE")]
        public String DNombre { get; set; }
        [Column("LOC")]
        public String Loc { get; set; }
    }
}

MDFS-4/NetCore/ProyectoCeroEF/Controllers/IndexController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoCeroEF.Models;
using ProyectoCeroEF.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoCeroEF.Controllers
{
    public class IndexController : Controller
    {
        HospitalRepository repository;
        public IndexController(HospitalRepository repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            List <Departamento> departamentos = repository.GetDepartamentos();
            return View(departamentos);
        }
    }
}

MDFS-4/NetCore/ProyectoCeroEF/Views/Shared/_Layout.cshtml
<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/signin.css" rel="stylesheet">

</head>

<body class="text-center">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <img src="~/assets/imgs/logogob.png" style="height:50px;width:150px" />
        <a class="navbar-brand" style="margin-left:30px" href="#">EMS ESPAÑA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li><a class="nav-link" asp-controller="Index" asp-action="Index">Departamentos</a></li>
            </ul>

        </div>
    </nav>
    @RenderBody()
</body>
<script src="~/js/popper.min.js"></script>
<script src="~/js/jquery-3.5.1.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
@RenderSection("script", false)

</html>