MDFS-4/NetCore/mvccore-master2/MvcCoreNuevo/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreNuevo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreNuevo.Controllers
{
    public class CochesController : Controller
    {
        private List<Coche> GetCoches()
        {
            Coche car = new Coche
            {
                IdCoche=1,
                Marca = "Audi",
                Modelo = "R8",
                VelocidadMaxima = 350
            };
            Coche car2 = new Coche
            {
                IdCoche = 2,
                Marca = "BMW",
                Modelo = "Serie S",
                VelocidadMaxima = 340
            };
            Coche car3 = new Coche
            {
                IdCoche = 3,
                Marca = "Msserati",
                Modelo = "Ray",
                VelocidadMaxima = 450
            };
            List<Coche> coches = new List<Coche>();
            coches.Add(car);
            coches.Add(car2);
            coches.Add(car3);

            return coches;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CochesAsincronos()
        {
            return View();
        }
        public IActionResult GetCochesPartial()
        {
            List<Coche> coches = this.GetCoches();
            return PartialView("_CochesPartial",coches);
        }
        public IActionResult DetallesCochePartial(int id)
        {
            Coche c = this.GetCoches().Where(x => x.IdCoche == id).FirstOrDefault();
            return PartialView("_DetallesCochePartial",c);
        }
    }
}

MDFS-4/NetCore/mvccore-master2/MvcCoreNuevo/Views/Coches/CochesAsincronos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@section scripts{ 
    <script>
        $(document).ready(function () {
            $("#botoncoches").click(function () {
                $("#capacoches").load("/Coches/GetCochesPartial")
            });
            $("#botoncocheID").click(function () {
                var id = $("#cajaid").val();
                $("#capacochedetalle").load("/Coches/DetallesCochePartial/"+id)
            });
        });
    </script>
}
<h1>Coches Asincronos</h1>
<button type="button" id="botoncoches">
    Mostrar coches
</button>
<br/>
<br/>
<input type="number" id="cajaid" class="form-control"/>
<br/>
<button type="button" id="botoncocheID">
    Mostrar detalles
</button>
<hr/>
<div id="capacoches" style="background-color:yellow"></div>
<div id="capacochedetalle" style="background-color:#03a2ff;padding:15px"></div>

MDFS-4/NetCore/mvccore-master2/MvcCoreNuevo/Views/Coches/Index.cshtml
@model IEnumerable<MvcCoreNuevo.Models.Coche>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="nav-link"
       asp-controller="Coches"
       asp-action="CochesAsincronos">Coches Asincronos</a>
</p>

MDFS-4/NetCore/mvccore-master2/MvcCoreNuevo/Views/Coches/_CochesPartial.cshtml
@model List<Coche>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Marca
            </th>
            <th>
                Modelo
            </th>
            <th>
                Velocidad Maxima
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VelocidadMaxima)
                </td>

            </tr>
        }
    </tbody>
</table>

MDFS-4/NetCore/mvccore-master2/MvcCoreNuevo/Views/Coches/_DetallesCochePartial.cshtml
@model Coche
<h1>Coche</h1>
<hr/>
<h4 style="color:blue">@Model.Marca</h4>
<h4 style="color:blue">@Model.Modelo</h4>
<h4 style="color:blue">Velocidad maxima: @Model.VelocidadMaxima km/h</h4>